import { QueryClient } from "@tanstack/react-query";

export const queryKeys = {
  auth: {
    sendOtp: (userName) => ["auth", "send-otp", userName],
    verifyOtp: (userName, otp) => ["auth", "verify-otp", userName, otp],
    logout: () => ["auth", "logout"],
  },
  admin: {
    domains: (roleId, languageCode, assessmentId = null) => [
      "admin",
      "domains",
      roleId,
      languageCode,
      assessmentId,
    ],
    criteriaQuestions: (subDomainId, roleId, languageCode) => [
      "admin",
      "criteria-questions",
      subDomainId,
      roleId,
      languageCode,
    ],
    subdomainQuestions: (subDomainId, roleId, languageCode = null, classNumber = null, section = null, subjectId = null) => [
      "admin",
      "subdomain-questions",
      subDomainId,
      roleId,
      languageCode,
      classNumber,
      section,
      subjectId,
    ],
    upsertDomain: () => ["admin", "upsert-domain"],
    upsertSubdomain: () => ["admin", "upsert-subdomain"],
    upsertQuestion: () => ["admin", "upsert-question"],
    upsertQuestionOption: () => ["admin", "upsert-question-option"],
    deleteDomain: () => ["admin", "delete-domain"],
    deleteQuestion: () => ["admin", "delete-question"],
    deleteQuestionOption: () => ["admin", "delete-question-option"],
    assessments: (academicYear) => ["admin", "assessments", academicYear],
  },
  school: {
    domains: (roleId, languageCode) => ["school", "domains", roleId, languageCode],
    schoolData: (schoolId, academicYear) => ["school", "school-data", schoolId, academicYear],
    classWiseSections: (userId, classNumber) => ["school", "class-wise-sections", userId, classNumber],
    schoolSections: (schoolId) => ["school", "school-sections", schoolId],
    submitSubdomainWiseAnswers: () => ["school", "submit-subdomain-wise-answers"],
    infrastructure: (schoolId) => ["school", "infrastructure", schoolId],
    updateInfrastructure: () => ["school", "update-infrastructure"],
  },
  inspector: {
    allocatedSchools: (districtId) => ["inspector", "allocated-schools", districtId],
    domains: (roleId, languageCode) => ["verifier", "domains", roleId, languageCode],
    subdomainQuestions: (subDomainId, roleId, languageCode = null, classNumber = null, section = null, subjectId = null) => [
      "verifier",
      "subdomain-questions",
      subDomainId,
      roleId,
      languageCode,
      classNumber,
      section,
      subjectId,
    ],
    submitAnswer: () => ["verifier", "submit-answer"],
    submitSubdomainWiseAnswers: () => ["verifier", "submit-subdomain-wise-answers"],
    schoolData: (schoolId, academicYear) => ["verifier", "school-data", schoolId, academicYear],
    schoolSections: (schoolId) => ["verifier", "school-sections", schoolId],
  },
  verifier: {
    domains: (roleId, languageCode, schoolId) => ["verifier", "domains", roleId, languageCode, schoolId],
    subdomainQuestions: (subDomainId, roleId, languageCode = null, classNumber = null, section = null, subjectId = null, schoolId = null) => [
      "verifier",
      "subdomain-questions",
      subDomainId,
      roleId,
      languageCode,
      classNumber,
      section,
      subjectId,
      schoolId,
    ],
    submitAnswer: () => ["verifier", "submit-answer"],
    submitSubdomainWiseAnswers: () => ["verifier", "submit-subdomain-wise-answers"],
    schoolData: (schoolId, academicYear) => ["verifier", "school-data", schoolId, academicYear],
    schoolSections: (schoolId) => ["verifier", "school-sections", schoolId],
    allocatedSchools: (districtId) => ["verifier", "allocated-schools", districtId],
    districts: () => ["verifier", "districts"],
    dashboard: (districtId) => ["verifier", "dashboard", districtId],
  },
  crc: {
    domains: (roleId, languageCode, schoolId) => ["crc", "domains", roleId, languageCode, schoolId],
    subdomainQuestions: (subDomainId, roleId, languageCode = null, classNumber = null, section = null, subjectId = null, schoolId = null) => [
      "crc",
      "subdomain-questions",
      subDomainId,
      roleId,
      languageCode,
      classNumber,
      section,
      subjectId,
      schoolId,
    ],
    submitAnswer: () => ["crc", "submit-answer"],
    submitSubdomainWiseAnswers: () => ["crc", "submit-subdomain-wise-answers"],
    schoolData: (schoolId, academicYear) => ["crc", "school-data", schoolId, academicYear],
    schoolSections: (schoolId) => ["crc", "school-sections", schoolId],
    allocatedSchools: (districtId) => ["crc", "allocated-schools", districtId],
    schoolList: (blockId, clusterId, villageId, status, page, limit) => [
      "crc",
      "school-list",
      blockId,
      clusterId,
      villageId,
      status,
      page,
      limit,
    ],
  },
};
